apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - regional-allocator-rbac.yaml
  - xonotic-fleet.yaml
  - xonotic-fleetautoscaler.yaml

images:
  - name: ghcr.io/nfnv/xonotic-server
    newTag: connectivity-checkpoint
