apiVersion: v1
kind: ServiceAccount
metadata:
  name: xonotic-regional-allocator
  namespace: xonotic-agones
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xonotic-regional-allocator
  namespace: xonotic-agones
rules:
  - apiGroups: ["allocation.agones.dev"]
    resources: ["gameserverallocations"]
    verbs: ["create", "get"]
  - apiGroups: ["agones.dev"]
    resources: ["fleets", "gameservers"]
    verbs: ["get", "list"]
  - apiGroups: ["agones.dev"]
    resources: ["gameservers"]
    verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xonotic-regional-allocator
  namespace: xonotic-agones
subjects:
  - kind: ServiceAccount
    name: xonotic-regional-allocator
    namespace: xonotic-agones
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xonotic-regional-allocator
---
apiVersion: v1
kind: Secret
metadata:
  name: xonotic-regional-allocator-token
  namespace: xonotic-agones
  annotations:
    kubernetes.io/service-account.name: xonotic-regional-allocator
type: kubernetes.io/service-account-token
