apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: xonotic-fleet
  namespace: xonotic-agones
spec:
  replicas: 2
  scheduling: Packed
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xonotic-fleet
        game: xonotic
    spec:
      container: server
      ports:
        - name: gameplay
          portPolicy: Dynamic
          containerPort: 26000
          protocol: UDP
      health:
        disabled: true
      template:
        metadata:
          labels:
            app: xonotic-fleet
            game: xonotic
        spec:
          containers:
            - name: server
              image: ghcr.io/nfnv/xonotic-server:connectivity-checkpoint
              imagePullPolicy: Always
              env:
                - name: XONOTIC_PORT
                  value: "26000"
                - name: XONOTIC_HOSTNAME
                  value: Xonotic Agones Fleet
                - name: XONOTIC_PUBLIC
                  value: "0"
                - name: XONOTIC_MAXPLAYERS
                  value: "8"
                - name: XONOTIC_RANDOM_START_MAP_ENABLE
                  value: "1"
                - name: XONOTIC_MAP_POOL
                  value: xoylent stormkeep darkzone drain
                - name: XONOTIC_AGONES_READY_ENABLE
                  value: "1"
                - name: XONOTIC_AGONES_READY_DELAY_SECONDS
                  value: "10"
              ports:
                - name: gameplay
                  containerPort: 26000
                  protocol: UDP
