apiVersion: apps/v1
kind: Deployment
metadata:
  name: xonotic-allocator-frontend
  namespace: xonotic-allocator-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: xonotic-allocator-frontend
  template:
    metadata:
      labels:
        app: xonotic-allocator-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/nfnv/xonotic-allocator-frontend:allocator-frontend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
