apiVersion: v1
kind: ConfigMap
metadata:
  name: xonotic-alloy-config
  namespace: xonotic-observability
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    discovery.kubernetes "pods" {
      role = "pod"

      selectors {
        role  = "pod"
        field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname)
      }
    }

    discovery.relabel "pod_logs" {
      targets = discovery.kubernetes.pods.targets

      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        action        = "replace"
        target_label  = "namespace"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        action        = "replace"
        target_label  = "pod"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        action        = "replace"
        target_label  = "container"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_app", "__meta_kubernetes_pod_label_app_kubernetes_io_name"]
        separator     = ";"
        regex         = `^([^;]+);.*$|^;(.+)$`
        replacement   = "$1$2"
        action        = "replace"
        target_label  = "app"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_label_server_pool_id"]
        action        = "replace"
        target_label  = "server_pool_id"
      }

      rule {
        source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
        separator     = "/"
        replacement   = "$1"
        action        = "replace"
        target_label  = "job"
      }

      rule {
        source_labels = ["__meta_kubernetes_pod_container_id"]
        regex         = `^(\S+):\/\/.+$`
        replacement   = "$1"
        action        = "replace"
        target_label  = "container_runtime"
      }
    }

    loki.source.kubernetes "pod_logs" {
      targets    = discovery.relabel.pod_logs.output
      forward_to = [loki.process.pod_logs.receiver]
    }

    loki.process "pod_logs" {
      stage.static_labels {
        values = {
          cluster = "xonotic-mvp",
          region  = "south-america",
        }
      }

      forward_to = [loki.write.local.receiver]
    }

    loki.write "local" {
      endpoint {
        url = "http://xonotic-loki.xonotic-observability.svc.cluster.local:3100/loki/api/v1/push"
      }
    }
