apiVersion: v1
kind: ConfigMap
metadata:
  name: xonotic-grafana-datasources
  namespace: xonotic-observability
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        orgId: 1
        version: 1
        type: prometheus
        access: proxy
        url: http://xonotic-prometheus.xonotic-observability.svc.cluster.local:9090
        isDefault: true
        editable: false
      - name: Loki
        uid: loki
        orgId: 1
        version: 1
        type: loki
        access: proxy
        url: http://xonotic-loki.xonotic-observability.svc.cluster.local:3100
        isDefault: false
        editable: false
