apiVersion: v1
kind: Service
metadata:
  name: xonotic-grafana
  namespace: xonotic-observability
spec:
  type: ClusterIP
  selector:
    app: xonotic-grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
