apiVersion: v1
kind: ConfigMap
metadata:
  name: xonotic-loki-config
  namespace: xonotic-observability
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
      log_level: info

    common:
      instance_addr: 127.0.0.1
      path_prefix: /var/loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules

    schema_config:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    limits_config:
      ingestion_rate_mb: 2
      ingestion_burst_size_mb: 4
      max_entries_limit_per_query: 5000
      max_query_lookback: 24h
      retention_period: 24h

    compactor:
      working_directory: /var/loki/compactor
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 1h
      retention_delete_worker_count: 10
      delete_request_store: filesystem

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 16

    analytics:
      reporting_enabled: false
