apiVersion: v1
kind: ConfigMap
metadata:
  name: xonotic-prometheus-config
  namespace: xonotic-observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: allocator-backend
        metrics_path: /metrics
        static_configs:
          - targets:
              - xonotic-allocator-backend.xonotic-allocator-backend.svc.cluster.local:8080

      - job_name: kube-state-metrics
        metrics_path: /metrics
        static_configs:
          - targets:
              - xonotic-kube-state-metrics.xonotic-observability.svc.cluster.local:8080

      - job_name: node-exporter
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - xonotic-observability
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: xonotic-node-exporter
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics

      - job_name: kubernetes-kubelet
        scheme: https
        metrics_path: /metrics
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics
          - source_labels: [__meta_kubernetes_node_name]
            target_label: node

      - job_name: kubernetes-cadvisor
        scheme: https
        metrics_path: /metrics/cadvisor
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
          - source_labels: [__meta_kubernetes_node_name]
            target_label: node
