apiVersion: v1
kind: ConfigMap
metadata:
  name: xonotic-prometheus-config
  namespace: xonotic-observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: allocator-backend
        metrics_path: /metrics
        static_configs:
          - targets:
              - xonotic-allocator-backend.xonotic-allocator-backend.svc.cluster.local:8080
