apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xonotic-postgres-data
  namespace: xonotic-allocator-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
